"""
Shared utility functions for the BioNexus Embeddings module.

This module collects small, dependency-light helper functions used across
``embedding_generator.py``, ``embedding_store.py``, ``embedding_search.py``,
``cache.py``, and ``embedding_manager.py``. Keeping these here avoids
duplicating logic (text normalization, hashing, chunking, vector math)
across those modules and keeps each of them focused on its single
responsibility.

Functions
---------
normalize_text
    Normalize whitespace in raw text prior to embedding.
compute_text_hash
    Compute a deterministic hash of a text string (used for cache keys).
compute_cache_key
    Compute a deterministic cache key from a model name and text.
chunk_text
    Split long text into overlapping chunks suitable for embedding.
validate_vector
    Validate that a vector is well-formed (non-empty, finite, correct
    dimension).
cosine_similarity
    Compute cosine similarity between two vectors.
"""

from __future__ import annotations

import hashlib
import logging
import math
import re

logger = logging.getLogger(__name__)


def normalize_text(text: str) -> str:
    """
    Normalize whitespace in a text string prior to embedding.

    Collapses runs of whitespace (spaces, tabs, newlines) into single
    spaces and strips leading/trailing whitespace. This ensures that
    trivially different whitespace formatting does not produce different
    cache keys or embeddings for semantically identical text.

    Parameters
    ----------
    text:
        The raw text to normalize.

    Returns
    -------
    str
        The normalized text.

    Raises
    ------
    ValueError
        If ``text`` is empty or whitespace-only.

    Examples
    --------
    >>> normalize_text("  Hello   world\\n")
    'Hello world'
    """
    if not text or not text.strip():
        raise ValueError("text must be a non-empty string.")

    return re.sub(r"\s+", " ", text).strip()


def compute_text_hash(text: str) -> str:
    """
    Compute a deterministic SHA-256 hash of a text string.

    The text is normalized (via :func:`normalize_text`) before hashing so
    that whitespace-only differences do not produce different hashes.

    Parameters
    ----------
    text:
        The text to hash.

    Returns
    -------
    str
        A hexadecimal SHA-256 digest string.

    Raises
    ------
    ValueError
        If ``text`` is empty or whitespace-only.
    """
    normalized = normalize_text(text)
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def compute_cache_key(model_name: str, text: str) -> str:
    """
    Compute a deterministic cache key for a (model, text) pair.

    Combining the model name into the key ensures that embeddings
    generated by different models are never confused with one another in
    a shared cache.

    Parameters
    ----------
    model_name:
        Identifier of the embedding model used (or to be used).
    text:
        The text that was (or will be) embedded.

    Returns
    -------
    str
        A deterministic cache key string.

    Raises
    ------
    ValueError
        If ``model_name`` or ``text`` is empty or whitespace-only.
    """
    if not model_name or not model_name.strip():
        raise ValueError("model_name must be a non-empty string.")

    text_hash = compute_text_hash(text)
    return f"{model_name}:{text_hash}"


def chunk_text(
    text: str,
    chunk_size: int = 1000,
    overlap: int = 100,
) -> list[str]:
    """
    Split long text into overlapping, whitespace-normalized chunks.

    Chunking is performed on normalized text using character-based
    windows. Overlap between consecutive chunks helps preserve context
    that would otherwise be lost at chunk boundaries, which is important
    for downstream Retrieval-Augmented Generation use cases.

    Parameters
    ----------
    text:
        The text to split into chunks.
    chunk_size:
        Maximum number of characters per chunk. Must be positive.
    overlap:
        Number of characters of overlap between consecutive chunks. Must
        be non-negative and strictly less than ``chunk_size``.

    Returns
    -------
    list[str]
        The list of text chunks, in order. If ``text`` (after
        normalization) is shorter than or equal to ``chunk_size``, a
        single-element list containing the whole normalized text is
        returned.

    Raises
    ------
    ValueError
        If ``text`` is empty, ``chunk_size`` is not positive, ``overlap``
        is negative, or ``overlap >= chunk_size``.
    """
    if chunk_size <= 0:
        raise ValueError(f"chunk_size must be positive, got {chunk_size}.")
    if overlap < 0:
        raise ValueError(f"overlap must be >= 0, got {overlap}.")
    if overlap >= chunk_size:
        raise ValueError(
            f"overlap ({overlap}) must be strictly less than "
            f"chunk_size ({chunk_size})."
        )

    normalized = normalize_text(text)

    if len(normalized) <= chunk_size:
        return [normalized]

    chunks: list[str] = []
    step = chunk_size - overlap
    start = 0
    text_length = len(normalized)

    while start < text_length:
        end = min(start + chunk_size, text_length)
        chunk = normalized[start:end].strip()
        if chunk:
            chunks.append(chunk)
        if end == text_length:
            break
        start += step

    return chunks


def validate_vector(vector: list[float], expected_dimension: int | None = None) -> None:
    """
    Validate that a vector is well-formed.

    Checks that the vector is non-empty, contains only finite numeric
    values (no NaN or infinity), and optionally matches an expected
    dimensionality.

    Parameters
    ----------
    vector:
        The vector to validate.
    expected_dimension:
        If provided, the vector's length must equal this value.

    Raises
    ------
    ValueError
        If the vector is empty, contains non-finite values, or does not
        match ``expected_dimension`` when provided.
    """
    if not vector:
        raise ValueError("vector must not be empty.")

    for index, value in enumerate(vector):
        if not math.isfinite(value):
            raise ValueError(
                f"vector contains a non-finite value at index {index}: {value}."
            )

    if expected_dimension is not None and len(vector) != expected_dimension:
        raise ValueError(
            f"vector has dimension {len(vector)}, expected {expected_dimension}."
        )


def cosine_similarity(vector_a: list[float], vector_b: list[float]) -> float:
    """
    Compute cosine similarity between two equal-length vectors.

    Parameters
    ----------
    vector_a:
        The first vector.
    vector_b:
        The second vector.

    Returns
    -------
    float
        The cosine similarity, in the range ``[-1.0, 1.0]``. Returns
        ``0.0`` if either vector has zero magnitude.

    Raises
    ------
    ValueError
        If the vectors are empty or have mismatched dimensions.
    """
    if not vector_a or not vector_b:
        raise ValueError("vectors must not be empty.")
    if len(vector_a) != len(vector_b):
        raise ValueError(
            f"Vector dimension mismatch: {len(vector_a)} vs {len(vector_b)}."
        )

    dot = sum(a * b for a, b in zip(vector_a, vector_b))
    norm_a = math.sqrt(sum(a * a for a in vector_a))
    norm_b = math.sqrt(sum(b * b for b in vector_b))

    if norm_a == 0.0 or norm_b == 0.0:
        return 0.0

    return dot / (norm_a * norm_b)


__all__: list[str] = [
    "normalize_text",
    "compute_text_hash",
    "compute_cache_key",
    "chunk_text",
    "validate_vector",
    "cosine_similarity",
]